train:
  fold: 5
  seed: 2020
  epochs: 10
  accum_iter: 2

scheduler:
  schd_batch_update: False
  schd_loss_update: False

data:
  train_batch: 16
  valid_batch: 32

model:
  model_arch: tf_efficientnet_b4_ns

optimizer:
  lr: 1e-4
  min_lr: 1e-6
  weight_decay: 1e-6

verbose_step: 1
img_size: 512
